# This is a basic workflow that is manually triggered

name: Manual Trigger

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Manual trigger digital ocean
        description: 'Manual trigger digital ocean'
        # Default value if no value is explicitly provided
        default: 'Manual trigger digital ocean'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NextJS app (Simple-NextJS)
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd /home/simple-nextjs
            git clone git@github.com:skd1993/simple-nextjs.git
            npm install
            npm run build
            npm run start
            echo 'Deployment successful to digital ocean'
            pm2 restart SimpleNestJS
